---
- name: Package Installation
  hosts: rundeck
  become: true
  tasks:
    - name: Install openjdk-17
      ansible.builtin.apt:
        name:
          - openjdk-17-jre-headless
        state: latest
