---
- name: Install Plex Media Server Exporter
  hosts: fiordland
  become: true

  tasks:
    - name: Ensure Docker is running
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

    - name: Run plex-media-server-exporter container
      community.docker.docker_container:
        name: plex-exporter
        image: ghcr.io/axsuul/plex-media-server-exporter:latest
        state: started
        restart_policy: unless-stopped
        network_mode: host
        env:
          PLEX_ADDR: "http://localhost:32400"
          PLEX_TOKEN: "{{ plex_token }}"
          PORT: "9594"
          METRICS_PREFIX: "plex"
          METRICS_MEDIA_COLLECTING_INTERVAL_SECONDS: "300"
